baseURL = 'https://patchneranartkomol.com/'
locale = 'en-us'
title = 'Patch Neranartkomol'
theme = 'PaperMod'
[[menu.main]]
  name = "Playlists"
  url = "/playlists/"
  weight = 10
[caches]
  [caches.images]
    dir = ':cacheDir/images'
