baseURL = 'https://patchneranartkomol.com/'
locale = 'en-us'
title = 'Patch Neranartkomol'
[[menu.main]]
  name = "Playlists"
  url = "/playlists/"
  weight = 10
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable=false

theme = ["hugo-PaperMod"]
